(chore): Use venv for all dev scripts

diff --git a/scripts/develop b/scripts/develop
--- a/scripts/develop
+++ b/scripts/develop
@@ -4,6 +4,14 @@ set -e
 
 cd "$(dirname "$0")/.."
 
+if [[ ! -f venv/bin/activate ]]; then
+    echo "ERROR: No venv, make sure you run setup first!"
+    exit 1
+fi
+
+source venv/bin/activate
+
+
 # Create config dir if not present
 if [[ ! -d "${PWD}/config" ]]; then
     mkdir -p "${PWD}/config"
