chore: Improve vscode and devcontainer debug setup
- use `uv` for pip requirements.
- Change debugpy calls to work with remote debugging HAOS
- settings.json to use devcontainer's venv in ~/vscode/.local/ha-env
  Also explicitly disabled unittests, enabled pytest per copilot req.
- configure scripts/setup and scripts/develop to allow setting venv
  location with $VENV, default to devcontainer's ~/vscode/.local...

Signed-off-by: Ashley Gittins <ash@ajg.net.au>

diff --git a/scripts/develop b/scripts/develop
--- a/scripts/develop
+++ b/scripts/develop
@@ -10,12 +10,12 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-#if [[ ! -f venv/bin/activate ]]; then
-#    echo "ERROR: No venv, make sure you run setup first!"
-#    exit 1
-#fi
-#
-#source venv/bin/activate
+if [[ ! -f "$VENV/bin/activate" ]]; then
+    echo "ERROR: No venv, make sure you run setup first!"
+    exit 1
+fi
+
+source $VENV/bin/activate
 
 
 # Create config dir if not present
